# Generated by Django 3.1 on 2020-08-22 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_pointstable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointstable',
            name='points',
            field=models.IntegerField(null=True),
        ),
    ]
